import { existsSync } from "node:fs";

const DOCS_DIR = ".docs";

export async function ensureDocsGitignored(): Promise<void> {
  await ensureDocsDirectoryGitignore();
  await ensureRootGitignoreEntry();
}

async function ensureDocsDirectoryGitignore(): Promise<void> {
  const docsGitignorePath = `${DOCS_DIR}/.gitignore`;
  if (!existsSync(docsGitignorePath)) {
    await Bun.write(docsGitignorePath, "*\n");
  }
}

async function ensureRootGitignoreEntry(): Promise<void> {
  const rootGitignorePath = ".gitignore";
  if (!existsSync(rootGitignorePath)) return;

  const content = await Bun.file(rootGitignorePath).text();
  if (content.includes(DOCS_DIR)) return;

  const lines = content.split("\n");
  const targetIndex = lines.findIndex((line) => line.trim() === "# Autogenerated");

  if (targetIndex === -1) {
    await Bun.write(rootGitignorePath, `${content}\n${DOCS_DIR}/\n`);
  } else {
    lines.splice(targetIndex + 1, 0, `${DOCS_DIR}/`);
    await Bun.write(rootGitignorePath, lines.join("\n"));
  }
}
