/**
 * Build-time script: compiles .mjml templates → TypeScript modules containing
 * the rendered HTML as an exported string. Run via `bun run build:emails`.
 *
 * Output files are committed so there is no runtime mjml dependency.
 */

import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import mjml2html from "mjml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatesDir = join(__dirname, "../src/templates");
const outDir = join(templatesDir, "compiled");

mkdirSync(outDir, { recursive: true });

const mjmlFiles = readdirSync(templatesDir).filter((f) => f.endsWith(".mjml"));

if (mjmlFiles.length === 0) {
  console.error("No .mjml files found in", templatesDir);
  process.exit(1);
}

for (const file of mjmlFiles) {
  const name = basename(file, ".mjml");
  const source = readFileSync(join(templatesDir, file), "utf-8");

  const { html, errors } = mjml2html(source, {
    validationLevel: "strict",
  });

  if (errors.length > 0) {
    for (const err of errors) {
      console.error(`[${file}]`, err.formattedMessage);
    }
    process.exit(1);
  }

  // Escape backticks and template literal sequences so the HTML is safe inside
  // a JS template literal.
  const escaped = html
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const outTs = `// AUTO-GENERATED by scripts/build-emails.ts — do not edit manually.
// Source: src/templates/${file}
// Regenerate: bun run build:emails (from packages/notifications)

export const html = \`${escaped}\`;
`;

  const outPath = join(outDir, `${name}.ts`);
  writeFileSync(outPath, outTs, "utf-8");
  console.log(`✓ compiled ${file} → compiled/${name}.ts`);
}
