import type { Kysely } from "kysely";

import type { Database } from "../../../types";

export async function persistUsersAndTeams(
  db: Kysely<Database>,
  now: number,
  realPasswordHash: string,
): Promise<void> {
  await db
    .insertInto("teams")
    .values([
      { id: 5, branch_id: 4, name: "Infinity Lima", created_at: now },
      { id: 6, branch_id: 4, name: "Infinity Chiclayo", created_at: now },
    ])
    .onConflict((oc) => oc.doNothing())
    .execute();

  await db
    .insertInto("users")
    .values([
      {
        id: 21,
        branch_id: 4,
        team_id: 5,
        username: "jorge.quezada",
        email: "jorge.quezada@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "JORGE ANDRES",
        first_surname: "QUEZADA",
        second_surname: "CORNEJO",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 22,
        branch_id: 4,
        team_id: 5,
        username: "karina.yalta",
        email: "karina.yalta@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "KARINA",
        first_surname: "YALTA",
        second_surname: "MENDOZA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 23,
        branch_id: 4,
        team_id: null,
        username: "luis.betalleluz",
        email: "luis.betalleluz@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "LUIS FERNANDO",
        first_surname: "BETALLELUZ",
        second_surname: "KALINOWSKI",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "supervisor",
        is_active: 1,
        created_at: now,
      },
      {
        id: 24,
        branch_id: 4,
        team_id: 5,
        username: "sebastian.salazar",
        email: "sebastian.salazar@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "SEBASTIAN ROMMEL",
        first_surname: "SALAZAR",
        second_surname: "MESTAS",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 25,
        branch_id: 4,
        team_id: 5,
        username: "giancarlo.aranguri",
        email: "giancarlo.aranguri@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "GIANCARLO ALEXANDER",
        first_surname: "ARANGURI",
        second_surname: "NUÑEZ",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 26,
        branch_id: 4,
        team_id: 5,
        username: "paola.lozano",
        email: "paola.lozano@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "LIZ PAOLA",
        first_surname: "LOZANO",
        second_surname: "RUIZ",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 27,
        branch_id: 4,
        team_id: 5,
        username: "veronica.banquez",
        email: "veronica.banquez@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "VERONICA VANESA",
        first_surname: "BANQUEZ",
        second_surname: "BARRETO",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 28,
        branch_id: 4,
        team_id: 5,
        username: "wendy.sarmiento",
        email: "wendy.sarmiento@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "WENDY CAROLINA",
        first_surname: "SARMIENTO",
        second_surname: "RODRIGUEZ",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 29,
        branch_id: 4,
        team_id: null,
        username: "victor.franco",
        email: "victor.franco@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "VICTOR ROBERTO",
        first_surname: "FRANCO",
        second_surname: "SAAVEDRA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "sales_manager",
        is_active: 1,
        created_at: now,
      },
      {
        id: 30,
        branch_id: 4,
        team_id: null,
        username: "jose.mendoza",
        email: "jose.mendoza@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "JOSE GREGORIO",
        first_surname: "MENDOZA",
        second_surname: "PEREIRA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "back_office",
        is_active: 1,
        created_at: now,
      },
      {
        id: 31,
        branch_id: 4,
        team_id: 5,
        username: "renato.santacruz",
        email: "renato.santacruz@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "RENATO",
        first_surname: "SANTA CRUZ",
        second_surname: "DURAND",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 32,
        branch_id: 4,
        team_id: 6,
        username: "francisco.suyon",
        email: "francisco.suyon@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "FRANCISCO ANDRES",
        first_surname: "SUYON",
        second_surname: "SANCHEZ",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 33,
        branch_id: 4,
        team_id: 6,
        username: "franco.fernandez",
        email: "franco.fernandez@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "ELVIS FRANCO",
        first_surname: "FERNANDEZ",
        second_surname: "FLORES",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 34,
        branch_id: 4,
        team_id: 6,
        username: "eber.montalvo",
        email: "eber.montalvo@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "EBER MOISES",
        first_surname: "MONTALVO",
        second_surname: "GUERRERO",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 35,
        branch_id: 4,
        team_id: 6,
        username: "pool.ortega",
        email: "pool.ortega@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "POOL ARIEL",
        first_surname: "ORTEGA",
        second_surname: "INGA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 36,
        branch_id: 4,
        team_id: 6,
        username: "jesus.avalos",
        email: "jesus.avalos@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "JESUS MARTIN",
        first_surname: "AVALOS",
        second_surname: "ROJAS",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 37,
        branch_id: 4,
        team_id: 5,
        username: "joyce.llanos",
        email: "joyce.llanos@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "JOYCE LICETH",
        first_surname: "LLANOS",
        second_surname: "ESPINOZA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 38,
        branch_id: 4,
        team_id: 6,
        username: "junior.cardozo",
        email: "junior.cardozo@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "JUNIOR EDINSON",
        first_surname: "CARDOZO",
        second_surname: "AGUILAR",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
      {
        id: 39,
        branch_id: 4,
        team_id: 5,
        username: "ricardo.nurena",
        email: "ricardo.nurena@infinitycorp.pe",
        password_hash: realPasswordHash,
        names: "RICARDO ARTURO",
        first_surname: "NUREÑA",
        second_surname: "ORTEGA",
        phone_e164: null,
        onboarding_completed_at: null,
        role: "executive",
        is_active: 1,
        created_at: now,
      },
    ])
    .onConflict((oc) => oc.doNothing())
    .execute();

  await db
    .insertInto("branch_supervisors")
    .values([{ branch_id: 4, user_id: 23, created_at: now }])
    .onConflict((oc) => oc.doNothing())
    .execute();

  await db
    .insertInto("back_office_assignments")
    .values([
      { back_office_user_id: 30, team_id: 5, assigned_at: now },
      { back_office_user_id: 30, team_id: 6, assigned_at: now },
    ])
    .onConflict((oc) => oc.doNothing())
    .execute();
}
