// AUTO-GENERATED by scripts/build-emails.ts — do not edit manually.
// Source: src/templates/invite.mjml + invite.txt
// Regenerate: bun run build:emails (from packages/notifications)

import { esc } from "../../utils.js";

export interface InviteEmailParams {
  fullName: string;
  role: string;
  inviteUrl: string;
  expiresAt: string;
}

export function renderInviteEmail(p: InviteEmailParams): { html: string; text: string } {
  return {
    html:
      `<!doctype html>
<html lang="und" dir="auto" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title></title>
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    <!--[if mso]>
    <noscript>
    <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
    </xml>
    </noscript>
    <![endif]-->
    <!--[if lte mso 11]>
    <style type="text/css">
      .mj-outlook-group-fix { width:100% !important; }
    </style>
    <![endif]-->
    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
    </style>
    
    
  
    
     
    <style type="text/css">
a {
        color: #333333;
      }
    </style>
    
  </head>
  <body style="word-spacing:normal;background-color:#f7f7f7;">
    
    
      <div
         aria-roledescription="email" style="background-color:#f7f7f7;" role="article" lang="und" dir="auto"
      >
        <!-- Spacer -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#f7f7f7" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#f7f7f7;background-color:#f7f7f7;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#f7f7f7;background-color:#f7f7f7;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:32px 0 0 0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:14px;line-height:1.6;text-align:left;color:#333333;"
      ></div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Card -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#ffffff" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#ffffff;background-color:#ffffff;margin:0px auto;max-width:600px;border-radius:8px;overflow:hidden;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;border-collapse:separate;"
        >
          <tbody>
            <tr>
              <td
                 style="border:1px solid #e8e8e8;border-radius:8px;direction:ltr;font-size:0px;padding:40px 48px;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:502px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          <!-- Heading -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;padding-bottom:24px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:20px;font-weight:600;line-height:1.6;text-align:left;color:#333333;"
      >Tu acceso al CRM está listo</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;padding-bottom:8px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:14px;line-height:1.6;text-align:left;color:#333333;"
      >Hola ` +
    esc(p.fullName) +
    `,</div>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;padding-bottom:24px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:14px;line-height:1.6;text-align:left;color:#333333;"
      >Se creó tu cuenta con el rol de <strong>` +
    esc(p.role) +
    `</strong>.
          Usa el botón de abajo para activar tu acceso
          antes de que venza el enlace.</div>
    
                </td>
              </tr>
            <!-- CTA -->
              <tr>
                <td
                   align="left" style="font-size:0px;padding:10px 25px;padding-bottom:24px;word-break:break-word;"
                >
                  
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;"
      >
        <tbody>
          <tr>
            <td
               align="center" bgcolor="#333333" role="presentation" style="border:none;border-radius:6px;cursor:auto;mso-padding-alt:12px 24px;background:#333333;" valign="middle"
            >
              <a
                 href="` +
    esc(p.inviteUrl) +
    `" style="display:inline-block;background:#333333;color:#ffffff;font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:14px;font-weight:500;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:12px 24px;mso-padding-alt:0px;border-radius:6px;" target="_blank"
              >
                Activar mi cuenta
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    
                </td>
              </tr>
            
              <tr>
                <td
                   align="left" style="font-size:0px;padding:0;padding-bottom:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:13px;line-height:1.6;text-align:left;color:#666666;"
      >Este enlace de activación vence el ` +
    esc(p.expiresAt) +
    `.
          Pasada esa fecha, pide a un administrador que reenvíe la invitación.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    <!-- Footer spacer -->
      
      <!--[if mso | IE]><table align="center" border="0" cellpadding="0" cellspacing="0" class="" role="presentation" style="width:600px;" width="600" bgcolor="#f7f7f7" ><tr><td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;"><![endif]-->
    
      
      <div  style="background:#f7f7f7;background-color:#f7f7f7;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#f7f7f7;background-color:#f7f7f7;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:32px 0;text-align:center;"
              >
                <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:600px;" ><![endif]-->
            
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:0;word-break:break-word;"
                >
                  
      <div
         style="font-family:Inter, 'Segoe UI', Helvetica, Arial, sans-serif;font-size:12px;line-height:1.6;text-align:center;color:#999999;"
      >Si no esperabas este correo, alguien ingresó tu dirección en el CRM.
          Puedes ignorarlo sin problema.</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          <!--[if mso | IE]></td></tr></table><![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      <!--[if mso | IE]></td></tr></table><![endif]-->
    
    
      </div>
    
  </body>
</html>
  `,
    text:
      "Hola " +
    p.fullName +
    ",\n\nSe creó tu cuenta con el rol " +
    p.role +
    ".\nActiva tu acceso aquí: " +
    p.inviteUrl +
    "\nEste enlace vence el " +
    p.expiresAt +
    ".\n",
  };
}
