import type { Permission, Role } from "../../src/lib/auth/rbac";

export const PERMISSION_MANIFEST: Record<Role, Permission[]> = {
  executive: [
    "leads:read",
    "leads:request",
    "quota:read",
    "sales:create",
    "sales:submit",
  ],
  supervisor: [
    "leads:read",
    "leads:request",
    "quota:read",
    "quota:allocate",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "team:read",
    "team:manage",
    "audit:read",
  ],
  back_office: ["sales:review", "sales:approve", "audit:read"],
  sales_manager: [
    "leads:read",
    "quota:read",
    "quota:allocate",
    "sales:review",
    "sales:approve",
    "team:read",
    "team:manage",
    "inventory:read",
    "audit:read",
    "admin:read",
    "admin:manage",
  ],
  logistics: ["inventory:read", "inventory:manage"],
  hr: ["hr:read", "hr:manage", "team:read"],
  admin: [
    "leads:read",
    "quota:read",
    "quota:allocate",
    "sales:review",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
  superuser: [
    "leads:read",
    "leads:request",
    "quota:read",
    "quota:allocate",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
};

export const SALES_ERROR_MANIFEST = {
  missingItems: "At least one product item is required before submission",
  missingDocuments: "At least one document is required before submission",
  missingInventoryLock:
    "An active inventory lock is required before submission",
  crossBranchReview: "Cannot review a sale from another branch",
} as const;

export const QUOTA_ERROR_MANIFEST = {
  duplicateDailyAllocation: "Quota already allocated for this date",
  exhausted2of2: "Quota exhausted: 2/2 used.",
} as const;
