import type { Permission, Role } from "../../src/lib/auth/access/rbac";

export const PERMISSION_MANIFEST: Record<Role, Permission[]> = {
  executive: [
    "leads:read",
    "leads:request",
    "quota:read",
    "sales:create",
    "sales:submit",
    "client_search:read",
  ],
  supervisor: [
    "leads:read",
    "leads:request",
    "quota:read",
    "quota:allocate",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "client_search:read",
    "team:read",
    "team:manage",
    "audit:read",
  ],
  back_office: ["sales:review", "sales:approve", "audit:read"],
  sales_manager: [
    "leads:read",
    "quota:read",
    "quota:allocate",
    "sales:review",
    "sales:approve",
    "team:read",
    "team:manage",
    "inventory:read",
    "client_search:read",
    "audit:read",
    "admin:read",
    "admin:manage",
  ],
  logistics: ["inventory:read", "inventory:manage"],
  hr: ["hr:read", "hr:manage", "team:read"],
  admin: [
    "leads:read",
    "quota:read",
    "quota:allocate",
    "sales:review",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "client_search:read",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
  superuser: [
    "leads:read",
    "leads:request",
    "quota:read",
    "quota:allocate",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "client_search:read",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
};

export const SALES_ERROR_MANIFEST = {
  missingAddresses: "At least one address is required",
  missingProducts: "At least one product is required",
  crossBranchConfirm: "Cannot confirm a sales record from another branch",
  emptyRejectionReason: "Rejection reason is required",
} as const;

export const QUOTA_ERROR_MANIFEST = {
  duplicateDailyAllocation: "Quota already allocated for this date",
  exhausted2of2: "Quota exhausted: 2/2 used.",
} as const;
