import type { Permission, Role } from "../../src/lib/auth/access/rbac";

export const PERMISSION_MANIFEST: Record<Role, Permission[]> = {
  executive: [
    "lead:work",
    "sales:create",
    "sales:submit",
    "search:use",
    "capacity:read:self",
    "capacity:request:self",
    "lead:register",
  ],
  supervisor: [
    "lead:work",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "search:use",
    "capacity:read:self",
    "capacity:request:self",
    "capacity:read:team",
    "capacity:manage",
    "capacity:approve",
    "team:read",
    "team:manage",
    "audit:read",
  ],
  back_office: [
    "sales:review",
    "sales:approve",
    "audit:read",
    "lead:view:all",
    "lead:review",
    "quotation:manage",
    "integration:manage",
  ],
  sales_manager: [
    "lead:work",
    "sales:review",
    "sales:approve",
    "search:use",
    "capacity:read:self",
    "capacity:request:self",
    "capacity:read:team",
    "capacity:manage",
    "capacity:approve",
    "capacity:policy:manage",
    "capacity:audit:read",
    "team:read",
    "team:manage",
    "inventory:read",
    "audit:read",
    "admin:read",
    "admin:manage",
  ],
  logistics: ["inventory:read", "inventory:manage"],
  hr: ["hr:read", "hr:manage", "team:read"],
  admin: [
    "lead:work",
    "sales:review",
    "search:use",
    "lead:register",
    "lead:view:all",
    "lead:review",
    "lead:reassign",
    "quotation:manage",
    "integration:manage",
    "capacity:read:self",
    "capacity:request:self",
    "capacity:read:team",
    "capacity:manage",
    "capacity:approve",
    "capacity:policy:manage",
    "capacity:audit:read",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
  superuser: [
    "lead:work",
    "sales:create",
    "sales:submit",
    "sales:review",
    "sales:approve",
    "lead:register",
    "lead:view:all",
    "lead:review",
    "lead:reassign",
    "quotation:manage",
    "integration:manage",
    "search:use",
    "capacity:read:self",
    "capacity:request:self",
    "capacity:read:team",
    "capacity:manage",
    "capacity:approve",
    "capacity:policy:manage",
    "capacity:audit:read",
    "team:read",
    "team:manage",
    "inventory:read",
    "inventory:manage",
    "hr:read",
    "hr:manage",
    "admin:read",
    "admin:manage",
    "audit:read",
  ],
};

export const SALES_ERROR_MANIFEST = {
  submitMissingAddresses: "At least one address is required before submit",
  submitMissingProducts: "At least one product is required before submit",
  crossBranchConfirm: "Cannot confirm a sales record from another branch",
  emptyRejectionReason: "Rejection reason is required",
} as const;

export const QUOTA_ERROR_MANIFEST = {
  duplicateDailyAllocation: "Quota already allocated for this date",
  exhausted2of2: "Quota exhausted: 2/2 used.",
} as const;
