// GENERATED FILE. DO NOT EDIT.
// Source: contracts/engine/search-projection.json
// Generator: tools/codegen/bin/generate.ts

export const SEARCH_PROJECTION_NAME = "search_projection" as const;
export const SEARCH_PROJECTION_PATHS = [
  "person.dni",
  "person.name",
  "person.ruc",
  "person.birth_date",
  "person.birth_place",
  "person.sex",
  "person.marital_status",
  "person.location_text",
  "person.ubigeo_code",
  "person.mother_name",
  "person.father_name",
  "person.email",
  "org.ruc",
  "org.name",
  "org.trade_name",
  "org.company_type",
  "org.status",
  "org.condition",
  "org.fiscal_address",
  "org.registration_date",
  "org.activity_start_date",
  "org.line_of_business",
  "org.economic_activity",
  "org.ubigeo_code",
  "org.department",
  "org.province",
  "org.district",
  "role.name",
  "role.start_date",
  "role.rep_doc_type",
  "role.rep_doc_number",
  "role.rep_name",
  "phones.primary",
  "phones.secondary",
  "phones.siblings",
] as const;
export type SearchProjectionPath = (typeof SEARCH_PROJECTION_PATHS)[number];

export const SEARCH_PROJECTION_NULLABLE_PATHS = [
  "person.name",
  "person.ruc",
  "person.birth_date",
  "person.birth_place",
  "person.sex",
  "person.marital_status",
  "person.location_text",
  "person.ubigeo_code",
  "person.mother_name",
  "person.father_name",
  "person.email",
  "org.ruc",
  "org.name",
  "org.trade_name",
  "org.company_type",
  "org.status",
  "org.condition",
  "org.fiscal_address",
  "org.registration_date",
  "org.activity_start_date",
  "org.line_of_business",
  "org.economic_activity",
  "org.ubigeo_code",
  "org.department",
  "org.province",
  "org.district",
  "role.name",
  "role.start_date",
  "role.rep_doc_type",
  "role.rep_doc_number",
  "role.rep_name",
  "phones.primary",
  "phones.secondary",
  "phones.siblings",
] as const;
export type SearchProjectionNullablePath =
  (typeof SEARCH_PROJECTION_NULLABLE_PATHS)[number];
