export const AUDIT_READER_MAX_LIMIT = 200;
export const AUDIT_READER_DEFAULT_LIMIT = 80;
export const AUDIT_READER_MAX_WINDOW_MINUTES = 60 * 24 * 30;
export const AUDIT_READER_DEFAULT_WINDOW_MINUTES = 1440;
