export {
  ABONO_BANKS,
  ACCOUNT_TYPE_KINDS,
  LEAD_PRIORITIES,
  LEAD_STATUSES,
  MODALIDAD_COBRO_KINDS,
  MONEDAS,
  isBcpBank,
  isLeadStage,
  isLeadStatus,
  isMoneda,
  type AbonoBank,
  type AccountTypeKind,
  type LeadPriority,
  type LeadStage,
  type LeadStatus,
  type ModalidadCobro,
  type Moneda,
  type ProductScope,
} from "./vocabulary";
export type { VenueDigitalConfig } from "./primitives";
export type {
  AssignableExecutivesInput,
  CreateLeadInput,
  LeadArtifactInput,
  LeadIdInput,
  LeadListFiltersInput,
  RequestQuotationInput,
  SaveCommercialScopeInput,
  SaveDigitalPolicyInput,
} from "./inputs";
export type {
  LeadCommandResult,
  LeadNegotiationFileView,
  LeadSaleProofFileView,
} from "./results";
export type {
  AssignableExecutiveView,
  LeadAvailableAction,
  LeadBlockingField,
  LeadBootstrapPreviewView,
  LeadDetailLeadView,
  LeadDetailNegotiationRequestView,
  LeadDetailQuotationView,
  LeadDetailVenueView,
  LeadDetailView,
  LeadListRowView,
  LeadListView,
  LeadTimelineItem,
} from "./views";
