import type { Kysely } from "kysely";

import type { Database } from "../../types";
import { stableSeedId } from "../shared/stable-id";
import { INFINITY_BRANCH_ID } from "./persist/branches-policies";

const INFINITY_LIMA_TEAM_ID = stableSeedId("team:infinity-lima");
const INFINITY_CHICLAYO_TEAM_ID = stableSeedId("team:infinity-chiclayo");
const LUIS_BETALLELUZ_ID = stableSeedId("installation-user:luis.betalleluz");
const JOSE_MENDOZA_ID = stableSeedId("installation-user:jose.mendoza");

export async function persistInstallationManifest(
  db: Kysely<Database>,
  now: Date,
  realPasswordHash: string,
): Promise<void> {
  await db
    .insertInto("teams")
    .values([
      {
        id: INFINITY_LIMA_TEAM_ID,
        branch_id: INFINITY_BRANCH_ID,
        name: "Infinity Lima",
        created_at: now,
      },
      {
        id: INFINITY_CHICLAYO_TEAM_ID,
        branch_id: INFINITY_BRANCH_ID,
        name: "Infinity Chiclayo",
        created_at: now,
      },
    ])
    .execute();

  await db
    .insertInto("users")
    .values([
      {
        id: stableSeedId("installation-user:jorge.quezada"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "jorge.quezada",
        email: "jorge.quezada@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "JORGE ANDRES",
        first_surname: "QUEZADA",
        second_surname: "CORNEJO",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:karina.yalta"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "karina.yalta",
        email: "karina.yalta@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "KARINA",
        first_surname: "YALTA",
        second_surname: "MENDOZA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: LUIS_BETALLELUZ_ID,
        branch_id: INFINITY_BRANCH_ID,
        team_id: null,
        username: "luis.betalleluz",
        email: "luis.betalleluz@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "LUIS FERNANDO",
        first_surname: "BETALLELUZ",
        second_surname: "KALINOWSKI",
        onboarding_completed_at: null,
        role: "supervisor",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:sebastian.salazar"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "sebastian.salazar",
        email: "sebastian.salazar@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "SEBASTIAN ROMMEL",
        first_surname: "SALAZAR",
        second_surname: "MESTAS",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:giancarlo.aranguri"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "giancarlo.aranguri",
        email: "giancarlo.aranguri@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "GIANCARLO ALEXANDER",
        first_surname: "ARANGURI",
        second_surname: "NUÑEZ",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:paola.lozano"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "paola.lozano",
        email: "paola.lozano@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "LIZ PAOLA",
        first_surname: "LOZANO",
        second_surname: "RUIZ",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:veronica.banquez"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "veronica.banquez",
        email: "veronica.banquez@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "VERONICA VANESA",
        first_surname: "BANQUEZ",
        second_surname: "BARRETO",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:wendy.sarmiento"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "wendy.sarmiento",
        email: "wendy.sarmiento@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "WENDY CAROLINA",
        first_surname: "SARMIENTO",
        second_surname: "RODRIGUEZ",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:victor.franco"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: null,
        username: "victor.franco",
        email: "victor.franco@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "VICTOR ROBERTO",
        first_surname: "FRANCO",
        second_surname: "SAAVEDRA",
        onboarding_completed_at: null,
        role: "sales_manager",
        is_active: true,
        created_at: now,
      },
      {
        id: JOSE_MENDOZA_ID,
        branch_id: INFINITY_BRANCH_ID,
        team_id: null,
        username: "jose.mendoza",
        email: "jose.mendoza@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "JOSE GREGORIO",
        first_surname: "MENDOZA",
        second_surname: "PEREIRA",
        onboarding_completed_at: null,
        role: "back_office",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:renato.santacruz"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "renato.santacruz",
        email: "renato.santacruz@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "RENATO",
        first_surname: "SANTA CRUZ",
        second_surname: "DURAND",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:francisco.suyon"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "francisco.suyon",
        email: "francisco.suyon@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "FRANCISCO ANDRES",
        first_surname: "SUYON",
        second_surname: "SANCHEZ",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:franco.fernandez"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "franco.fernandez",
        email: "franco.fernandez@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "ELVIS FRANCO",
        first_surname: "FERNANDEZ",
        second_surname: "FLORES",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:eber.montalvo"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "eber.montalvo",
        email: "eber.montalvo@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "EBER MOISES",
        first_surname: "MONTALVO",
        second_surname: "GUERRERO",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:pool.ortega"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "pool.ortega",
        email: "pool.ortega@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "POOL ARIEL",
        first_surname: "ORTEGA",
        second_surname: "INGA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:jesus.avalos"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "jesus.avalos",
        email: "jesus.avalos@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "JESUS MARTIN",
        first_surname: "AVALOS",
        second_surname: "ROJAS",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:joyce.llanos"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "joyce.llanos",
        email: "joyce.llanos@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "JOYCE LICETH",
        first_surname: "LLANOS",
        second_surname: "ESPINOZA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:junior.cardozo"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        username: "junior.cardozo",
        email: "junior.cardozo@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "JUNIOR EDINSON",
        first_surname: "CARDOZO",
        second_surname: "AGUILAR",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:ricardo.nurena"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "ricardo.nurena",
        email: "ricardo.nurena@infinitycorp.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "RICARDO ARTURO",
        first_surname: "NUREÑA",
        second_surname: "ORTEGA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:david.duran"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: null,
        username: "david.duran",
        email: "david.duran@onechannel.pe",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "DAVID",
        first_surname: "DURAN",
        second_surname: "",
        onboarding_completed_at: null,
        role: "admin",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:luisa.ramirez"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "luisa.ramirez",
        email: "luisa.ramirez@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "LUISA ISABEL",
        first_surname: "RAMIREZ",
        second_surname: "VILCHEZ",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:erick.azucena"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "erick.azucena",
        email: "erick.azucena@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "ERICK DIMAS",
        first_surname: "AZUCENA",
        second_surname: "CHIRRE",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:christian.arango"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "christian.arango",
        email: "christian.arango@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "CHRISTIAN",
        first_surname: "ARANGO",
        second_surname: "CANDIOTTI",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:ray.castillo"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "ray.castillo",
        email: "ray.castillo@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "RAY ABEL",
        first_surname: "CASTILLO",
        second_surname: "CALIXTO",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:victor.tineo"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "victor.tineo",
        email: "victor.tineo@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "VICTOR RAUL",
        first_surname: "TINEO",
        second_surname: "AYALA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
      {
        id: stableSeedId("installation-user:carlos.lazarte"),
        branch_id: INFINITY_BRANCH_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        username: "carlos.lazarte",
        email: "carlos.lazarte@culqinegocios.com",
        password_hash: realPasswordHash,
        password_change_required: true,
        names: "CARLOS JHONATAN",
        first_surname: "LAZARTE",
        second_surname: "ARIZOLA",
        onboarding_completed_at: null,
        role: "executive",
        is_active: true,
        created_at: now,
      },
    ])
    .execute();

  await db
    .insertInto("branch_supervisors")
    .values([
      {
        branch_id: INFINITY_BRANCH_ID,
        user_id: LUIS_BETALLELUZ_ID,
        created_at: now,
      },
    ])
    .execute();

  await db
    .insertInto("back_office_assignments")
    .values([
      {
        back_office_user_id: JOSE_MENDOZA_ID,
        team_id: INFINITY_LIMA_TEAM_ID,
        assigned_at: now,
      },
      {
        back_office_user_id: JOSE_MENDOZA_ID,
        team_id: INFINITY_CHICLAYO_TEAM_ID,
        assigned_at: now,
      },
    ])
    .execute();
}
