import * as auth from "./schema/modules/auth.types";
import * as capacity from "./schema/modules/capacity.types";
import * as core from "./schema/modules/core.types";
import * as extensions from "./schema/modules/extensions.types";
import * as files from "./schema/modules/files.types";
import * as identity from "./schema/modules/identity.types";
import * as integrations from "./schema/modules/integrations.types";
import * as leads from "./schema/modules/leads.types";
import * as negotiation from "./schema/modules/negotiation.types";
import * as notifications from "./schema/modules/notifications.types";
import * as observability from "./schema/modules/observability.types";
import * as platform from "./schema/modules/platform.types";
import * as sales from "./schema/modules/sales.types";
import * as search from "./schema/modules/search.types";
import * as workflow from "./schema/modules/workflow.types";

export * from "./schema/modules/auth.types";
export * from "./schema/modules/capacity.types";
export * from "./schema/modules/core.types";
export * from "./schema/modules/identity.types";
export * from "./schema/modules/leads.types";
export * from "./schema/modules/extensions.types";
export * from "./schema/modules/files.types";
export * from "./schema/modules/integrations.types";
export * from "./schema/modules/negotiation.types";
export * from "./schema/modules/notifications.types";
export * from "./schema/modules/observability.types";
export * from "./schema/modules/platform.types";
export * from "./schema/modules/sales.types";
export * from "./schema/modules/search.types";
export * from "./schema/modules/workflow.types";

export interface Database {
  branches: core.BranchesTable;
  teams: core.TeamsTable;
  organizations: core.OrganizationsTable;
  branch_supervisors: core.BranchSupervisorsTable;
  back_office_assignments: core.BackOfficeAssignmentsTable;
  login_flows: auth.LoginFlowsTable;
  passkeys: auth.PasskeysTable;
  webauthn_challenges: auth.WebauthnChallengesTable;
  user_oauth_accounts: auth.UserOAuthAccountsTable;
  password_reset_tokens: auth.PasswordResetTokensTable;
  user_sessions: auth.UserSessionsTable;
  request_sessions: auth.RequestSessionsTable;
  user_totp_factors: auth.UserTotpFactorsTable;
  user_totp_recovery_codes: auth.UserTotpRecoveryCodesTable;
  user_invites: auth.UserInvitesTable;
  auth_funnel_events: auth.AuthFunnelEventsTable;
  users: identity.UsersTable;
  contacts: leads.ContactsTable;
  lead_assignments: leads.LeadAssignmentsTable;
  interaction_logs: leads.InteractionLogsTable;
  search_capacity_grants: capacity.SearchCapacityGrantsTable;
  search_usage_reservations: capacity.SearchUsageReservationsTable;
  search_usage_commits: capacity.SearchUsageCommitsTable;
  lead_capacity_grants: capacity.LeadCapacityGrantsTable;
  lead_usage_reservations: capacity.LeadUsageReservationsTable;
  lead_usage_commits: capacity.LeadUsageCommitsTable;
  capacity_requests: capacity.CapacityRequestsTable;
  lead_policy_defaults: capacity.LeadPolicyDefaultsTable;
  lead_policy_overrides: capacity.LeadPolicyOverridesTable;
  search_policy_defaults: capacity.SearchPolicyDefaultsTable;
  search_policy_overrides: capacity.SearchPolicyOverridesTable;
  notification_contacts: notifications.NotificationContactsTable;
  notification_preferences: notifications.NotificationPreferencesTable;
  notification_campaigns: notifications.NotificationCampaignsTable;
  notification_recipients: notifications.NotificationRecipientsTable;
  notification_jobs: notifications.NotificationJobsTable;
  notification_deliveries: notifications.NotificationDeliveriesTable;
  app_notifications: notifications.AppNotificationsTable;
  extension_handoffs: extensions.ExtensionHandoffsTable;
  extension_installation_sessions: extensions.ExtensionInstallationSessionsTable;
  extension_runtime_events: extensions.ExtensionRuntimeEventsTable;
  extension_executive_statuses: extensions.ExtensionExecutiveStatusesTable;
  client_search_views: search.ClientSearchViewsTable;
  search_enrichment_jobs: search.SearchEnrichmentJobsTable;
  search_enrichment_overlays: search.SearchEnrichmentOverlaysTable;
  search_enrichment_completion_outbox: search.SearchEnrichmentCompletionOutboxTable;
  audit_logs: platform.AuditLogsTable;
  audit_action_policies: platform.AuditActionPoliciesTable;
  report_export_jobs: platform.ReportExportJobsTable;
  report_export_downloads: platform.ReportExportDownloadsTable;
  action_observations: observability.ActionObservationsTable;
  agent_status_logs: observability.AgentStatusLogsTable;
  action_rate_limit_counters: observability.ActionRateLimitCountersTable;
  auth_throttle_counters: observability.AuthThrottleCountersTable;
  auth_events: observability.AuthEventsTable;
  workflow_leads: workflow.WorkflowLeadsTable;
  workflow_tipo_producto_kinds: workflow.WorkflowTipoProductoKindsTable;
  workflow_modalidad_cobro_kinds: workflow.WorkflowModalidadCobroKindsTable;
  workflow_lead_commercial_inputs: workflow.WorkflowLeadCommercialInputsTable;
  workflow_quotations: workflow.WorkflowQuotationsTable;
  workflow_sales: workflow.WorkflowSalesTable;
  workflow_lead_assignments: workflow.WorkflowLeadAssignmentsTable;
  workflow_lead_favorites: workflow.WorkflowLeadFavoritesTable;
  workflow_history_events: workflow.WorkflowHistoryEventsTable;
  workflow_audit_logs: workflow.WorkflowAuditLogsTable;
  lead_sourcing_policies: workflow.LeadSourcingPoliciesTable;
  workflow_integration_jobs: integrations.WorkflowIntegrationJobsTable;
  workflow_integration_import_rows: integrations.WorkflowIntegrationImportRowsTable;
  workflow_integration_outbox_needs_executive_input: integrations.WorkflowIntegrationOutboxNeedsExecutiveInputTable;
  workflow_integration_outbox_ready_for_quotation: integrations.WorkflowIntegrationOutboxReadyForQuotationTable;
  workflow_artifacts: files.WorkflowArtifactsTable;
  file_assets: files.FileAssetsTable;
  artifact_file_bindings: files.ArtifactFileBindingsTable;
  artifact_events: files.ArtifactEventsTable;
  artifact_download_tokens: files.ArtifactDownloadTokensTable;
  workflow_sale_proof_files: files.WorkflowSaleProofFilesTable;
  workflow_negotiation_requests: negotiation.WorkflowNegotiationRequestsTable;
  workflow_negotiation_files: negotiation.WorkflowNegotiationFilesTable;
  workflow_sale_venues: sales.WorkflowSaleVenuesTable;
  workflow_sale_venue_accounts: sales.WorkflowSaleVenueAccountsTable;
  workflow_currency_kinds: sales.WorkflowCurrencyKindsTable;
  workflow_account_type_kinds: sales.WorkflowAccountTypeKindsTable;
  workflow_abono_banks: sales.WorkflowAbonoBanksTable;
}
