import * as auth from "./schema/modules/auth.types";
import * as capacity from "./schema/modules/capacity.types";
import * as contactAssignments from "./schema/modules/contact-assignments.types";
import * as core from "./schema/modules/core.types";
import * as extensions from "./schema/modules/extensions.types";
import * as files from "./schema/modules/files.types";
import * as fulfillment from "./schema/modules/fulfillment.types";
import * as identity from "./schema/modules/identity.types";
import * as integrations from "./schema/modules/integrations.types";
import * as merchantStats from "./schema/modules/merchant-stats.types";
import * as notifications from "./schema/modules/notifications.types";
import * as observability from "./schema/modules/observability.types";
import * as organization from "./schema/modules/organization.types";
import * as platform from "./schema/modules/platform.types";
import * as pricing from "./schema/modules/pricing.types";
import * as sales from "./schema/modules/sales.types";
import * as search from "./schema/modules/search.types";
import * as workflow from "./schema/modules/workflow.types";

export * from "./schema/modules/auth.types";
export * from "./schema/modules/capacity.types";
export * from "./schema/modules/contact-assignments.types";
export * from "./schema/modules/core.types";
export * from "./schema/modules/identity.types";
export * from "./schema/modules/organization.types";
export * from "./schema/modules/extensions.types";
export * from "./schema/modules/files.types";
export * from "./schema/modules/fulfillment.types";
export * from "./schema/modules/integrations.types";
export * from "./schema/modules/merchant-stats.types";
export * from "./schema/modules/notifications.types";
export * from "./schema/modules/observability.types";
export * from "./schema/modules/platform.types";
export * from "./schema/modules/pricing.types";
export * from "./schema/modules/sales.types";
export * from "./schema/modules/search.types";
export * from "./schema/modules/workflow.types";

export interface Database {
  branches: core.BranchesTable;
  teams: core.TeamsTable;
  branch_supervisors: core.BranchSupervisorsTable;
  back_office_assignments: core.BackOfficeAssignmentsTable;
  organizations: organization.OrganizationsTable;
  people: organization.PeopleTable;
  organization_people: organization.OrganizationPeopleTable;
  organization_person_roles: organization.OrganizationPersonRolesTable;
  login_flows: auth.LoginFlowsTable;
  passkeys: auth.PasskeysTable;
  webauthn_challenges: auth.WebauthnChallengesTable;
  user_oauth_accounts: auth.UserOAuthAccountsTable;
  password_reset_tokens: auth.PasswordResetTokensTable;
  user_sessions: auth.UserSessionsTable;
  request_sessions: auth.RequestSessionsTable;
  user_totp_factors: auth.UserTotpFactorsTable;
  recovery_code_set: auth.RecoveryCodeSetTable;
  recovery_code: auth.RecoveryCodeTable;
  user_invites: auth.UserInvitesTable;
  auth_funnel_events: auth.AuthFunnelEventsTable;
  users: identity.UsersTable;
  contact_assignments: contactAssignments.ContactAssignmentsTable;
  contact_cadence: contactAssignments.ContactCadenceTable;
  interaction_logs: contactAssignments.InteractionLogsTable;
  search_capacity_grants: capacity.SearchCapacityGrantsTable;
  search_usage_reservations: capacity.SearchUsageReservationsTable;
  search_usage_commits: capacity.SearchUsageCommitsTable;
  lead_capacity_grants: capacity.LeadCapacityGrantsTable;
  lead_usage_reservations: capacity.LeadUsageReservationsTable;
  lead_usage_commits: capacity.LeadUsageCommitsTable;
  capacity_requests: capacity.CapacityRequestsTable;
  lead_policy_defaults: capacity.LeadPolicyDefaultsTable;
  lead_policy_overrides: capacity.LeadPolicyOverridesTable;
  search_policy_defaults: capacity.SearchPolicyDefaultsTable;
  search_policy_overrides: capacity.SearchPolicyOverridesTable;
  user_channel_addresses: notifications.UserChannelAddressesTable;
  notification_opt_outs: notifications.NotificationOptOutsTable;
  notification_deliveries: notifications.NotificationDeliveriesTable;
  app_notifications: notifications.AppNotificationsTable;
  notification_intents: notifications.NotificationIntentsTable;
  whatsapp_sessions: notifications.WhatsAppSessionsTable;
  kapso_webhook_deliveries: notifications.KapsoWebhookDeliveriesTable;
  whatsapp_inbound_events: notifications.WhatsAppInboundEventsTable;
  outbound_whatsapp_messages: notifications.OutboundWhatsAppMessagesTable;
  extension_handoffs: extensions.ExtensionHandoffsTable;
  extension_installation_sessions: extensions.ExtensionInstallationSessionsTable;
  extension_runtime_events: extensions.ExtensionRuntimeEventsTable;
  extension_executive_statuses: extensions.ExtensionExecutiveStatusesTable;
  client_search_views: search.ClientSearchViewsTable;
  company_registry_record: search.CompanyRegistryRecordTable;
  events: platform.EventsTable;
  audit_action_policies: platform.AuditActionPoliciesTable;
  action_observations: observability.ActionObservationsTable;
  agent_status_logs: observability.AgentStatusLogsTable;
  action_rate_limit_counters: observability.ActionRateLimitCountersTable;
  auth_throttle_counters: observability.AuthThrottleCountersTable;
  auth_events: observability.AuthEventsTable;
  workflow_leads: workflow.WorkflowLeadsTable;
  workflow_idempotency_keys: workflow.WorkflowIdempotencyKeysTable;
  workflow_collection_mode_kinds: workflow.WorkflowCollectionModeKindsTable;
  workflow_lead_digital_policy: workflow.WorkflowLeadDigitalPolicyTable;
  workflow_rate_proposals: pricing.WorkflowRateProposalsTable;
  workflow_rate_proposal_policies: pricing.WorkflowRateProposalPoliciesTable;
  workflow_rate_revisions: pricing.WorkflowRateRevisionsTable;
  workflow_rate_revision_files: pricing.WorkflowRateRevisionFilesTable;
  workflow_lead_assignments: workflow.WorkflowLeadAssignmentsTable;
  workflow_lead_favorites: workflow.WorkflowLeadFavoritesTable;
  lead_sourcing_policies: workflow.LeadSourcingPoliciesTable;
  workflow_integration_jobs: integrations.WorkflowIntegrationJobsTable;
  workflow_integration_import_rows: integrations.WorkflowIntegrationImportRowsTable;
  merchant_reports: merchantStats.MerchantReportsTable;
  merchant_report_rejections: merchantStats.MerchantReportRejectionsTable;
  merchant_sales: merchantStats.MerchantSalesTable;
  merchant_sale_gpv: merchantStats.MerchantSaleGpvTable;
  merchant_monthly_gpv: merchantStats.MerchantMonthlyGpvTable;
  merchant_monthly_attribution: merchantStats.MerchantMonthlyAttributionTable;
  merchant_targets: merchantStats.MerchantTargetsTable;
  file_assets: files.FileAssetsTable;
  file_download_tokens: files.FileDownloadTokensTable;
  workflow_sale_proof_files: files.WorkflowSaleProofFilesTable;
  lead_fulfillment_orders: fulfillment.LeadFulfillmentOrdersTable;
  lead_fulfillment_units: fulfillment.LeadFulfillmentUnitsTable;
  lead_fulfillment_documents: fulfillment.LeadFulfillmentDocumentsTable;
  workflow_lead_venues: sales.WorkflowLeadVenuesTable;
  workflow_lead_venue_accounts: sales.WorkflowLeadVenueAccountsTable;
  workflow_currency_kinds: sales.WorkflowCurrencyKindsTable;
  workflow_account_type_kinds: sales.WorkflowAccountTypeKindsTable;
  workflow_settlement_banks: sales.WorkflowSettlementBanksTable;
}
