export { createNotificationService } from "./service";
export type {
  NotificationChannel,
  NotificationSendInput,
  NotificationService,
  NotificationsConfig,
} from "./types";

// Email template renderers — generated by build:emails, not committed to git.
// Run `bun run build:emails` if these imports are missing.
export { renderInviteEmail } from "./templates/compiled/invite.js";
export type { InviteEmailParams } from "./templates/compiled/invite.js";
export { renderCampaignEmail } from "./templates/compiled/campaign.js";
export type { CampaignEmailParams } from "./templates/compiled/campaign.js";
