// GENERATED FILE. DO NOT EDIT.
// Source: contracts/engine/doc-projection.json
// Generator: tools/codegen/bin/generate.ts

export const DOC_PROJECTION_PATHS = [
  "doc.doc_type",
  "doc.doc_number",
  "doc.name",
  "doc.ruc",
  "doc.birth_date",
  "doc.birth_place",
  "doc.sex",
  "doc.marital_status",
  "doc.location_text",
  "doc.ubigeo_code",
  "doc.mother_name",
  "doc.father_name",
  "doc.email",
  "org.ruc",
  "org.name",
  "org.trade_name",
  "org.company_type",
  "org.status",
  "org.condition",
  "org.fiscal_address",
  "org.registration_date",
  "org.activity_start_date",
  "org.line_of_business",
  "org.economic_activity",
  "org.ubigeo_code",
  "org.department",
  "org.province",
  "org.district",
  "role.name",
  "role.start_date",
  "role.rep_doc_type",
  "role.rep_doc_number",
  "role.rep_name",
  "phones.primary",
  "phones.secondary",
  "phones.siblings",
] as const;
